### PR TITLE
Extraction Lab supports MFM Seeds & Produce

### PR DESCRIPTION
**Pull request by Royal-Jelly**
Values may need some minor tweaking in the future, but at the moment are reasonable.

Fixes Issue #8 

Fair to say the next to tackle is the xenostation, wish me luck ~

### CODE REVIEW

**Comment by ColonolNutty** [comment]
Have you tested some of these in game?

**Comment by Royal-Jelly** [comment]
I'll double check the ones that have two extractions, best to be safe I guess

**Comment by Royal-Jelly** [comment]
yeah something is up with the script that is running on the extractor 

Thanks for the quick save i'll troubleshoot this and let you know when its safe to merge

**Comment by Royal-Jelly** [comment]
okay well I may have rushed it sorry if I almost caused issues *laughs* It should be safe to merge now

**Comment by ColonolNutty** [comment]
Let me know how that goes and we'll see about getting it merged in.

**Pull request merged**
